### ISSUE TITLE
readme的文档写错了吧

### ISSUE THREAD

**Issue by xyz-fly** [scwang90/SmartRefreshHorizontal#1]
文档中让引用：com.scwang.smartrefresh.layout.SmartRefreshHorizontal
但实际上是 com.scwang.smartrefresh.horizontal.SmartRefreshHorizontal

**Comment by wojiaojay123** [comment]
报错：java.lang.IllegalAccessError: Method 'void com.scwang.smartrefresh.layout.SmartRefreshLayout.onFinishInflate()' is inaccessible to class 'com.scwang.smartrefresh.horizontal.SmartRefreshHorizontal

**Comment by scwang90** [comment]
文档已经重新整理
