### ISSUE TITLE
androidx 的recyclerview使用布局错乱

### ISSUE THREAD

**Issue by AndroidLMY** [scwang90/SmartRefreshHorizontal#10]

**Comment by scwang90** [comment]
注意 Horizontal 的版本和 Smart 的版本要匹配，并且 注意不要重复依赖两个 Smart

**Comment by AndroidLMY** [comment]
已经解决了，谢谢大大😁😁😁------------------ 原始邮件 ------------------
发件人: "树朾"<notifications@github.com>
发送时间: 2019年8月16日(星期五) 中午11:34
收件人: "scwang90/SmartRefreshHorizontal"<SmartRefreshHorizontal@noreply.github.com>;
抄送: "AndroidLMY"<465008238@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [scwang90/SmartRefreshHorizontal] androidx 的recyclerview使用布局错乱 (#10)



注意 Horizontal 的版本和 Smart 的版本要匹配，并且 注意不要重复依赖两个 Smart
 
&mdash;
