### ISSUE TITLE
有一定概率RecyclerView的内容显示不出来

### ISSUE THREAD

**Issue by amosyo1994** [scwang90/SmartRefreshHorizontal#12]
有一定概率RecyclerView的内容显示不出来，调用notifyDataChanged之后，Adapter的getItemCount也没调用。

但换成SmartRefresh就没问题。

**Comment by HanGao1** [comment]
我出现了类似的问题  我嵌套了viewpager,滑动的时候如果先刷新，则必现向左滑动时，直接调用了onloadmore,无语

**Comment by scwang90** [comment]
新版本已发布
