### ISSUE TITLE
header或foot显示问题。

### ISSUE THREAD

**Issue by ProfessionalMe** [scwang90/SmartRefreshHorizontal#14]
请问作者，那个左滑的提示，左滑刷新不觉得看着很别扭嘛，Textview旋转了，那看的时候也得横着看，能不能textview不旋转，里面的字竖着显示呢，就像这样：

左
滑
刷
新

**Comment by HanGao1** [comment]
+1所以这是一个不完善的库

**Comment by scwang90** [comment]
新版本发布，解决，参考demo中的设置方法
