### ISSUE TITLE
高度不支持wrap_content

### ISSUE THREAD

**Issue by DancingDuck** [scwang90/SmartRefreshHorizontal#16]
SmartRefreshHorizontal  高度设置成wrap_content无法显示内容

**Comment by chenjiaren145** [comment]
我也遇到了这个问题，难受。

**Comment by chenjiaren145** [comment]
> SmartRefreshHorizontal 高度设置成wrap_content无法显示内容

我发现在外面嵌套一层布局可以解决这个问题

**Comment by DancingDuck** [comment]
@chenjiaren145 谢谢老哥回复解决方案   我之前的需求是横向刷新 没用这个刷新交互了-0_0-

**Comment by duov** [comment]
@chenjiaren145请问是如何嵌套的啊

**Comment by scwang90** [comment]
已经修复 新版本发布
