### ISSUE TITLE
SmartRefreshHorizontal布局问题

### ISSUE THREAD

**Issue by BryantZp** [scwang90/SmartRefreshHorizontal#18]
SmartRefreshHorizontal布局之后，宽度设置的是match_parent，但是实际上只占了一部分宽度，另一部分就空置了，

**Comment by BryantZp** [comment]
打扰了，使用发现SmartRefreshHorizontal的外层，使用RelativeLayout会有上面的问题，使用LinearLayout则不会

**Comment by scwang90** [comment]
新版本已优化
