### ISSUE TITLE
好像是包名对不上吧

### ISSUE THREAD

**Issue by wojiaojay123** [scwang90/SmartRefreshHorizontal#2]
报错：java.lang.IllegalAccessError: Method 'void com.scwang.smartrefresh.layout.SmartRefreshLayout.onFinishInflate()' is inaccessible to class 'com.scwang.smartrefresh.horizontal.SmartRefreshHorizontal

**Comment by scwang90** [comment]
SmartRefreshHorizontal 对 Smart 的版本有要求
Horizontal:1.0.0-beta-1
Layout:1.1.0-beta-1
