### ISSUE TITLE
加载更多滚动recyclerview加载更多动画不能隐藏

### ISSUE THREAD

**Issue by yangyinggithub** [scwang90/SmartRefreshHorizontal#32]
apk-demo里面的加载更多过程中滚动recyclerview加载更多动画会隐藏 实际上加载更多滚动recyclerview加载更多动画固定不动
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0-beta-1'  (会隐藏动画)
implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0'（不会隐藏）

请问这个问题如何解决

**Comment by yangyinggithub** [comment]
找到问题了MaterialHeader中onMoving方法
if (mState == RefreshState.Refreshing) {
            return;
}
导致的

**Comment by scwang90** [comment]
MaterialHeader 作为 Footer 的话，可以配合 Smart 的 setEnableAutoLoadMore（false）来使用

**Comment by scwang90** [comment]
MaterialHeader 设计的时候，就是在刷新时，滚动列表，滚球位置不动。但是如果 MaterialHeader 作为 Footer  的时候，球不位置不懂，确实不妥，源码也没有做这个适配。
建议使用 MaterialHeader 做Footer 的时候，自己写一个 MaterialFooter来继承 MaterialHeader在 onMoving中自己移动位置即可
