### ISSUE TITLE
有坑啊，依赖方式自动导入的 代码有异常

### ISSUE THREAD

**Issue by blueskky** [scwang90/SmartRefreshHorizontal#6]
通过gradle方式自动带入的代码，SmartRefreshHorizontal 没有实现RefreshLayout 接口中带三个参数的 finishRefresh(int delayed, boolean success, Boolean noMoreData); 方法，导致inflate xml 报错

只能把代码下载下来导入，实现这个方法才能正常使用。作者改下吧，因为对SmartRefreshLayout的信任跑来用这个的，没想到有坑啊

**Comment by scwang90** [comment]
新版本 1.0.0-beta-1 发布修复，匹配的 smart 版本是 1.1.0-beta-1

**Comment by blueskky** [comment]
真棒
