### ISSUE TITLE
内部创建的SmartRefreshImpl复制了错误的状态

### ISSUE THREAD

**Issue by vickyleu** [scwang90/SmartRefreshHorizontal#9]
如果SmartRefreshHorizontal初始状态为GONE的情况下,impl也直接GONE,且id是直接复制的,然后在运行时修改Horizontal为Visible时,impl依然是GONE,需要实现setVisible方法的重写,以同步状态

**Comment by scwang90** [comment]
新版本发布，已去掉 impl 的机制
